import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { HomeContainer, MainContainer } from '../styles/StyledComponents.js';

import { RootContextProvider } from '../contexts/RootContext.js';
import CoinSearch from '../components/CoinSearch.js';

const Home: NextPage = () => {
  return (
    <RootContextProvider>
      <HomeContainer>
        <Head>
          <title>RainbowKit App</title>
          <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
          />
          <link href="/favicon.ico" rel="icon" />
        </Head>
        <MainContainer>
          <ConnectButton />
          <h1 className={styles.title}>
            Welcome to <a href="">Ammalgam</a>!
          </h1>
          <CoinSearch />
        </MainContainer>
      </HomeContainer>
    </RootContextProvider>
  );
};

export default Home;
